type JsonRecord = Record<string, unknown>;
const text = (value: unknown, min: number, max: number, field: string) => { if (typeof value !== 'string') throw new Error(`invalid_${field}`); const result=value.trim(); if(result.length<min||result.length>max||/<\/?[a-z][^>]*>/i.test(result))throw new Error(`invalid_${field}`); return result; };
const optionalText = (value: unknown, max: number, field: string) => value == null || value === '' ? undefined : text(value,1,max,field);
const url = (value: unknown, field: string) => { const result=text(value,8,2048,field); try{const parsed=new URL(result);if(!['http:','https:'].includes(parsed.protocol))throw new Error();}catch{throw new Error(`invalid_${field}`)} return result; };
export function validSlug(value: unknown){if(typeof value!=='string'||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(value)||value.length>120)throw new Error('invalid_slug');return value;}
export function validUuid(value: unknown,field='id'){if(typeof value!=='string'||!/^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(value))throw new Error(`invalid_${field}`);return value;}
export function validateArticlePayload(input:unknown,workspaceId:string,articleId:string){
  if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('invalid_payload');const payload=input as JsonRecord;const slug=validSlug(payload.slug);const coverInput=payload.coverData as JsonRecord|undefined;let coverData:JsonRecord;
  if(coverInput?.kind==='preset'&&['signal','layers','orbit'].includes(String(coverInput.preset)))coverData={kind:'preset',preset:coverInput.preset};
  else if(coverInput?.kind==='image'){const path=text(coverInput.path,10,500,'cover_path');if(!path.startsWith(`${workspaceId}/${articleId}/`))throw new Error('invalid_cover_path');const coverUrl=url(coverInput.url,'cover_url');const storageBase=Deno.env.get('SUPABASE_URL');if(!storageBase||!coverUrl.startsWith(`${storageBase}/storage/v1/object/public/article-covers/`)||!decodeURIComponent(new URL(coverUrl).pathname).endsWith(`/article-covers/${path}`))throw new Error('invalid_cover_url');coverData={kind:'image',path,url:coverUrl,alt:text(coverInput.alt,2,180,'cover_alt')};}else throw new Error('invalid_cover');
  if(!Array.isArray(payload.sections)||payload.sections.length<1||payload.sections.length>30)throw new Error('invalid_sections');const ids=new Set<string>();
  const sections=payload.sections.map((item,sectionIndex)=>{if(!item||typeof item!=='object'||Array.isArray(item))throw new Error('invalid_section');const section=item as JsonRecord;const id=validSlug(section.id);if(ids.has(id))throw new Error('duplicate_section_id');ids.add(id);if(!Array.isArray(section.paragraphs)||section.paragraphs.length<1||section.paragraphs.length>12)throw new Error('invalid_paragraphs');const paragraphs=section.paragraphs.map((item,index)=>text(item,1,5000,`paragraph_${sectionIndex}_${index}`));const bullets=section.bullets==null?undefined:Array.isArray(section.bullets)&&section.bullets.length<=20?section.bullets.map((item,index)=>text(item,1,500,`bullet_${sectionIndex}_${index}`)):(()=>{throw new Error('invalid_bullets')})();const callout=optionalText(section.callout,1200,'callout');return{id,title:text(section.title,2,220,'section_title'),paragraphs,...(bullets?.length?{bullets}:{}),...(callout?{callout}:{})};});
  if(!Array.isArray(payload.sources)||payload.sources.length>20)throw new Error('invalid_sources');const sources=payload.sources.map((item,index)=>{if(!item||typeof item!=='object'||Array.isArray(item))throw new Error('invalid_source');const source=item as JsonRecord;return{label:text(source.label,2,220,`source_label_${index}`),href:url(source.href,`source_url_${index}`)}});
  const readingText=String(payload.readingMinutes||'').replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d)));const reading=Number(payload.readingMinutesValue??readingText.match(/\d+/)?.[0]);if(!Number.isInteger(reading)||reading<1||reading>180)throw new Error('invalid_reading_minutes');const publishedAt=typeof payload.publishedAt==='string'&&!Number.isNaN(Date.parse(payload.publishedAt))?payload.publishedAt:new Date().toISOString();
  return{slug,title:text(payload.title,5,180,'title'),excerpt:text(payload.excerpt,20,600,'excerpt'),category:text(payload.category,2,80,'category'),publishedAt,publishedLabel:'',readingMinutesValue:reading,readingMinutes:`${reading} دقیقه مطالعه`,cover:coverData.kind==='preset'?coverData.preset:'signal',coverData,authorName:text(payload.authorName||'تحریریه پیکسل',2,120,'author_name'),authorSubtitle:text(payload.authorSubtitle||'راهنمای عملی برای تصمیم بهتر',2,180,'author_subtitle'),seoTitle:text(payload.seoTitle||payload.title,5,180,'seo_title'),seoDescription:text(payload.seoDescription||payload.excerpt,20,320,'seo_description'),ogDescription:text(payload.ogDescription||payload.excerpt,20,320,'og_description'),ctaTitle:text(payload.ctaTitle,3,180,'cta_title'),ctaText:text(payload.ctaText,10,600,'cta_text'),ctaLabel:text(payload.ctaLabel,2,100,'cta_label'),ctaService:text(payload.ctaService,2,160,'cta_service'),ctaLocation:`article-${slug}-cta`,sections,sources,modifiedAt:typeof payload.modifiedAt==='string'?payload.modifiedAt:publishedAt};
}
export function articleErrorStatus(code:string){if(code==='unauthorized')return 401;if(code==='forbidden')return 403;if(code==='article_not_found')return 404;if(code==='slug_locked'||code==='slug_exists'||code==='deploy_not_retryable')return 409;if(code.startsWith('invalid_')||code==='duplicate_section_id')return 422;return 500;}
