import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react';
import { NavLink, useNavigate, useParams } from 'react-router-dom';
import { Icon } from '../Icons';
import { ArticleDetailContent } from '../ArticlesPage';
import type { ArticleRecord, ArticleSection } from '../articles';
import { formatPersianDate, toPersianNumber } from './format';
import { invokeFunction, requireSupabase } from './supabase';
import type { CmsArticle, Membership } from './types';
import '../articles.css';

type RouteProps = { membership: Membership; preview: boolean; refreshKey: number; refresh(): void };
type EditableArticle = ArticleRecord & { readingMinutesValue: number };

const statusLabels = { draft: 'پیش‌نویس', published: 'منتشرشده', archived: 'آرشیوشده' } as const;
const deployLabels = { idle: '', pending: 'در صف انتشار', requested: 'درخواست ساخت ارسال شد', failed: 'خطای انتشار' } as const;

function emptyArticle(id: string): EditableArticle {
  const now = new Date().toISOString();
  return { slug: '', title: '', excerpt: '', category: '', publishedAt: now, publishedLabel: '', readingMinutes: '۱ دقیقه مطالعه', readingMinutesValue: 1, cover: 'signal', coverData: { kind: 'image', url: '', alt: '', path: '' }, authorName: 'تحریریه پیکسل', authorSubtitle: 'راهنمای عملی برای تصمیم بهتر', seoTitle: '', seoDescription: '', ogDescription: '', modifiedAt: now, ctaTitle: '', ctaText: '', ctaLabel: '', ctaService: '', ctaLocation: `article-${id}-cta`, sections: [{ id: 'section-1', title: '', paragraphs: [''] }], sources: [] };
}

function estimateReading(article: EditableArticle) {
  const content = [article.title, article.excerpt, ...article.sections.flatMap(section => [section.title, ...section.paragraphs, ...(section.bullets || []), section.callout || ''])].join(' ');
  return Math.max(1, Math.ceil(content.split(/\s+/).filter(Boolean).length / 180));
}

function pageHeader(eyebrow: string, title: string, description?: string, action?: React.ReactNode) {
  return <div className="page-header"><div><span>{eyebrow}</span><h1>{title}</h1>{description && <p>{description}</p>}</div>{action && <div className="page-action">{action}</div>}</div>;
}

export function ArticlesList({ membership, preview, refreshKey }: RouteProps) {
  const [rows, setRows] = useState<CmsArticle[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'all'|CmsArticle['status']>('all');
  useEffect(() => { let active=true; if(preview){setRows([]);setLoading(false);return;} setLoading(true); requireSupabase().from('articles').select('*').eq('workspace_id',membership.workspace_id).order('sort_order').order('updated_at',{ascending:false}).then(({data,error})=>{if(!active)return;if(error)setError('دریافت مقالات انجام نشد.');else setRows((data||[]) as CmsArticle[]);setLoading(false)});return()=>{active=false}},[membership.workspace_id,preview,refreshKey]);
  const visible=useMemo(()=>rows.filter(row=>(filter==='all'||row.status===filter)&&(!query||`${row.draft_payload.title} ${row.slug} ${row.draft_payload.category}`.toLowerCase().includes(query.toLowerCase()))),[rows,filter,query]);
  return <>{pageHeader('مجله پیکسل','مدیریت مقالات','پیش‌نویس‌ها را آماده کنید؛ انتشار نهایی فقط با تأیید مدیر انجام می‌شود.',<NavLink className="crm-primary" to="/articles/new">مقاله جدید <Icon name="plus" size={17}/></NavLink>)}
    <div className="article-toolbar"><label className="search-field"><Icon name="search" size={18}/><span className="sr-only">جست‌وجو</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="جست‌وجوی عنوان یا دسته‌بندی"/></label><div className="segmented" role="group" aria-label="فیلتر وضعیت">{([['all','همه'],['draft','پیش‌نویس'],['published','منتشرشده'],['archived','آرشیو']] as const).map(([value,label])=><button key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}</div></div>
    {loading?<div className="skeleton-list" aria-label="در حال بارگذاری"><i/><i/><i/></div>:error?<div className="notice error" role="alert">{error}</div>:visible.length===0?<section className="empty-state"><span><Icon name="spark" size={22}/></span><h2>مقاله‌ای در این وضعیت نیست</h2><p>اولین پیش‌نویس را بسازید تا فهرست مجله از همین‌جا مدیریت شود.</p></section>:<div className="article-admin-list">{visible.map(row=>{const changed=JSON.stringify(row.draft_payload)!==JSON.stringify(row.published_payload);return <article key={row.id}><div><span className={`article-status ${row.status}`}>{statusLabels[row.status]}</span><h2>{row.draft_payload.title}</h2><p><bdi>{row.slug}</bdi> · {row.draft_payload.category}</p><small>آخرین ویرایش {formatPersianDate(row.updated_at,true)}</small></div><div className="article-row-state">{row.status==='published'&&changed&&<span>تغییرات منتشرنشده</span>}{row.deployment_status!=='idle'&&<span className={row.deployment_status}>{deployLabels[row.deployment_status]}</span>}</div><NavLink className="crm-secondary small" to={`/articles/${row.id}/edit`}>ویرایش</NavLink></article>})}</div>}
  </>;
}

export function ArticleEditor({ membership, preview, refresh }: RouteProps) {
  const params=useParams();const navigate=useNavigate();const isNew=!params.id;const[id]=useState(()=>params.id||crypto.randomUUID());const[payload,setPayload]=useState<EditableArticle>(()=>emptyArticle(id));const[row,setRow]=useState<CmsArticle|null>(null);const[loading,setLoading]=useState(!isNew);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[message,setMessage]=useState('');const[dirty,setDirty]=useState(false);const[previewOpen,setPreviewOpen]=useState(false);const[uploading,setUploading]=useState(false);
  const previewDialogRef=useRef<HTMLDivElement>(null);const previewCloseRef=useRef<HTMLButtonElement>(null);
  useEffect(()=>{if(isNew||preview){setLoading(false);return}let active=true;requireSupabase().from('articles').select('*').eq('workspace_id',membership.workspace_id).eq('id',id).maybeSingle().then(({data,error})=>{if(!active)return;if(error||!data)setError('مقاله پیدا نشد.');else{const article=data as CmsArticle;setRow(article);const reading=article.draft_payload.readingMinutesValue||Number(String(article.draft_payload.readingMinutes).replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d))))||1;setPayload({...article.draft_payload,readingMinutesValue:reading});}setLoading(false)});return()=>{active=false}},[id,isNew,membership.workspace_id,preview]);
  useEffect(()=>{const before=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=''}};const links=(event:MouseEvent)=>{const anchor=(event.target as Element).closest('a[href]');if(dirty&&anchor&&anchor instanceof HTMLAnchorElement&&anchor.origin===location.origin&&!confirm('تغییرات ذخیره نشده‌اند. از صفحه خارج می‌شوید؟'))event.preventDefault()};addEventListener('beforeunload',before);document.addEventListener('click',links,true);return()=>{removeEventListener('beforeunload',before);document.removeEventListener('click',links,true)}},[dirty]);
  useEffect(()=>{if(!previewOpen)return;const previous=document.activeElement instanceof HTMLElement?document.activeElement:null;const previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';previewCloseRef.current?.focus();const keyboard=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();setPreviewOpen(false);return}if(event.key!=='Tab')return;const focusable=Array.from(previewDialogRef.current?.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),input:not([disabled]),textarea:not([disabled]),select:not([disabled]),[tabindex]:not([tabindex="-1"])')||[]);if(focusable.length===0){event.preventDefault();previewDialogRef.current?.focus();return}const first=focusable[0];const last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener('keydown',keyboard);return()=>{document.removeEventListener('keydown',keyboard);document.body.style.overflow=previousOverflow;previous?.focus()}},[previewOpen]);
  const set=<K extends keyof EditableArticle>(key:K,value:EditableArticle[K])=>{setPayload(current=>({...current,[key]:value}));setDirty(true);setMessage('')};
  const updateSections=(sections:ArticleSection[])=>{setPayload(current=>{const next={...current,sections} as EditableArticle;const reading=estimateReading(next);return{...next,readingMinutesValue:reading,readingMinutes:`${reading} دقیقه مطالعه`}});setDirty(true)};
  async function save(){setSaving(true);setError('');try{const normalized={...payload,sections:payload.sections.map(section=>({...section,paragraphs:section.paragraphs.map(item=>item.trim()).filter(Boolean),bullets:section.bullets?.map(item=>item.trim()).filter(Boolean)})),seoTitle:payload.seoTitle||`${payload.title} | پیکسل`,seoDescription:payload.seoDescription||payload.excerpt,ogDescription:payload.ogDescription||payload.excerpt,readingMinutes:`${payload.readingMinutesValue} دقیقه مطالعه`};const data=await invokeFunction<{article:CmsArticle}>('save-article-draft',{workspace_id:membership.workspace_id,id,payload:normalized});if(!data)throw new Error('empty_response');setRow(data.article);setPayload({...data.article.draft_payload,readingMinutesValue:normalized.readingMinutesValue});setDirty(false);setMessage('پیش‌نویس ذخیره شد.');refresh();if(isNew)navigate(`/articles/${id}/edit`,{replace:true});return data.article;}catch{setError('ذخیره پیش‌نویس انجام نشد. فیلدهای ضروری و slug را بررسی کنید.');return null}finally{setSaving(false)}}
  async function publish(){const saved=dirty||!row?await save():row;if(!saved)return;setSaving(true);setError('');try{await invokeFunction('publish-article',{workspace_id:membership.workspace_id,id});setMessage('نسخه منتشرشده ثبت شد و درخواست ساخت سایت ارسال شد.');setDirty(false);refresh();}catch{setError('انتشار کامل نشد. تنظیم Deploy Hook یا اعتبار داده‌ها را بررسی کنید.')}finally{setSaving(false)}}
  async function archive(){if(!confirm('این مقاله از خروجی بعدی سایت حذف و آرشیو شود؟'))return;setSaving(true);try{await invokeFunction('archive-article',{workspace_id:membership.workspace_id,id});refresh();navigate('/articles')}catch{setError('آرشیو مقاله انجام نشد.')}finally{setSaving(false)}}
  async function retry(){setSaving(true);try{await invokeFunction('retry-article-deploy',{workspace_id:membership.workspace_id,id});setMessage('درخواست ساخت سایت دوباره ارسال شد.');refresh()}catch{setError('ارسال دوباره درخواست انتشار انجام نشد.')}finally{setSaving(false)}}
  async function uploadCover(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setError('');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){setError('تصویر باید JPG، PNG یا WebP و حداکثر ۵ مگابایت باشد.');return}const objectUrl=URL.createObjectURL(file);try{const dimensions=await new Promise<{width:number;height:number}>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve({width:image.naturalWidth,height:image.naturalHeight});image.onerror=reject;image.src=objectUrl});if(dimensions.width<1200||dimensions.height<630){setError('ابعاد کاور باید حداقل ۱۲۰۰ در ۶۳۰ پیکسل باشد.');return}setUploading(true);const extension=file.name.split('.').pop()?.toLowerCase()||'webp';const path=`${membership.workspace_id}/${id}/${crypto.randomUUID()}.${extension}`;const client=requireSupabase();const uploaded=await client.storage.from('article-covers').upload(path,file,{contentType:file.type,upsert:false});if(uploaded.error)throw uploaded.error;const publicUrl=client.storage.from('article-covers').getPublicUrl(path).data.publicUrl;set('coverData',{kind:'image',path,url:publicUrl,alt:payload.coverData?.kind==='image'?payload.coverData.alt:payload.title});}catch{setError('آپلود کاور انجام نشد.')}finally{URL.revokeObjectURL(objectUrl);setUploading(false);event.target.value=''}}
  if(loading)return <div className="skeleton-list"><i/><i/><i/></div>;
  const locked=Boolean(row?.published_at);const canPublish=membership.role==='admin';
  return <>{pageHeader(isNew?'مقاله جدید':'ویرایش مقاله',payload.title||'پیش‌نویس بدون عنوان',row?`${statusLabels[row.status]} · آخرین ویرایش ${formatPersianDate(row.updated_at,true)}`:'مقاله پس از ذخیره در فهرست ظاهر می‌شود.',<div className="header-actions"><button type="button" className="crm-secondary" disabled={saving} onClick={()=>setPreviewOpen(true)}>پیش‌نمایش</button><button type="button" className="crm-secondary" disabled={saving||!dirty} onClick={()=>void save()}>{saving?'در حال ذخیره…':'ذخیره'}</button>{canPublish&&<button type="button" className="crm-primary" disabled={saving} onClick={()=>void publish()}>انتشار <Icon name="arrow" size={17}/></button>}</div>)}
    {message&&<div className="notice success" role="status">{message}</div>}{error&&<div className="notice error" role="alert">{error}</div>}{row?.deployment_status==='failed'&&canPublish&&<div className="notice warning">درخواست ساخت سایت ناموفق بوده است. <button className="text-button" onClick={()=>void retry()}>تلاش دوباره</button></div>}
    <div className="article-editor-layout"><form className="article-editor" onSubmit={event=>{event.preventDefault();void save()}}>
      <EditorPanel title="اطلاعات اصلی"><label>عنوان<input className="crm-field" required maxLength={180} value={payload.title} onChange={event=>set('title',event.target.value)}/></label><label>آدرس مقاله (slug)<input className="crm-field" dir="ltr" required disabled={locked} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={payload.slug} onChange={event=>set('slug',event.target.value.toLowerCase().replace(/[^a-z0-9-]/g,''))}/>{locked&&<small>برای حفظ URL و SEO پس از اولین انتشار قفل شده است.</small>}</label><label>خلاصه<textarea className="crm-field" required rows={4} maxLength={600} value={payload.excerpt} onChange={event=>set('excerpt',event.target.value)}/></label><div className="editor-grid"><label>دسته‌بندی<input className="crm-field" required maxLength={80} value={payload.category} onChange={event=>set('category',event.target.value)}/></label><label>زمان مطالعه<input className="crm-field" type="number" min="1" max="180" value={payload.readingMinutesValue} onChange={event=>set('readingMinutesValue',Number(event.target.value))}/></label></div></EditorPanel>
      <EditorPanel title="کاور مقاله"><label className="cover-upload">تصویر کاور<input type="file" accept="image/jpeg,image/png,image/webp" onChange={event=>void uploadCover(event)}/><span>{uploading?'در حال آپلود…':'انتخاب تصویر ۱۲۰۰×۶۳۰ یا بزرگ‌تر'}</span></label>{payload.coverData?.kind==='image'&&payload.coverData.url&&<img className="cover-preview" src={payload.coverData.url} alt="پیش‌نمایش کاور"/>}{payload.coverData?.kind==='image'&&<label>متن جایگزین<input className="crm-field" required maxLength={180} value={payload.coverData.alt} onChange={event=>set('coverData',{...payload.coverData!,alt:event.target.value} as EditableArticle['coverData'])}/></label>}{payload.coverData?.kind==='preset'&&<p className="legacy-cover-note">این مقاله از کاور گرافیکی فعلی پیکسل استفاده می‌کند. با آپلود تصویر، کاور جدید جایگزین می‌شود.</p>}</EditorPanel>
      <EditorPanel title="نویسنده"><div className="editor-grid"><label>نام نویسنده<input className="crm-field" required value={payload.authorName||''} onChange={event=>set('authorName',event.target.value)}/></label><label>توضیح نویسنده<input className="crm-field" required value={payload.authorSubtitle||''} onChange={event=>set('authorSubtitle',event.target.value)}/></label></div></EditorPanel>
      <EditorPanel title="بدنه مقاله" action={<button type="button" className="crm-secondary small" onClick={()=>updateSections([...payload.sections,{id:`section-${payload.sections.length+1}`,title:'',paragraphs:['']}])}>افزودن بخش</button>}><div className="article-section-editor">{payload.sections.map((section,index)=><section key={`${section.id}-${index}`}><header><strong>بخش {toPersianNumber(index+1)}</strong><div><button type="button" disabled={index===0} aria-label="انتقال بخش به بالا" onClick={()=>{const next=[...payload.sections];[next[index-1],next[index]]=[next[index],next[index-1]];updateSections(next)}}>↑</button><button type="button" disabled={index===payload.sections.length-1} aria-label="انتقال بخش به پایین" onClick={()=>{const next=[...payload.sections];[next[index+1],next[index]]=[next[index],next[index+1]];updateSections(next)}}>↓</button><button type="button" className="danger" aria-label="حذف بخش" disabled={payload.sections.length===1} onClick={()=>updateSections(payload.sections.filter((_,itemIndex)=>itemIndex!==index))}>×</button></div></header><div className="editor-grid"><label>عنوان بخش<input className="crm-field" required value={section.title} onChange={event=>updateSections(payload.sections.map((item,itemIndex)=>itemIndex===index?{...item,title:event.target.value}:item))}/></label><label>شناسه فهرست<input className="crm-field" dir="ltr" pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required value={section.id} onChange={event=>updateSections(payload.sections.map((item,itemIndex)=>itemIndex===index?{...item,id:event.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'')}:item))}/></label></div><label>پاراگراف‌ها <small>هر پاراگراف در یک خط جدا</small><textarea className="crm-field" required rows={7} value={section.paragraphs.join('\n')} onChange={event=>updateSections(payload.sections.map((item,itemIndex)=>itemIndex===index?{...item,paragraphs:event.target.value.split('\n')}:item))}/></label><label>فهرست اختیاری <small>هر مورد در یک خط</small><textarea className="crm-field" rows={4} value={(section.bullets||[]).join('\n')} onChange={event=>updateSections(payload.sections.map((item,itemIndex)=>itemIndex===index?{...item,bullets:event.target.value.split('\n').filter(Boolean)}:item))}/></label><label>نقل‌قول برجسته<textarea className="crm-field" rows={3} value={section.callout||''} onChange={event=>updateSections(payload.sections.map((item,itemIndex)=>itemIndex===index?{...item,callout:event.target.value||undefined}:item))}/></label></section>)}</div></EditorPanel>
      <EditorPanel title="منابع" action={<button type="button" className="crm-secondary small" onClick={()=>set('sources',[...payload.sources,{label:'',href:''}])}>افزودن منبع</button>}><div className="source-editor">{payload.sources.length===0&&<p>منبعی ثبت نشده است.</p>}{payload.sources.map((source,index)=><div key={index}><input className="crm-field" aria-label={`عنوان منبع ${index+1}`} placeholder="عنوان منبع" value={source.label} onChange={event=>set('sources',payload.sources.map((item,itemIndex)=>itemIndex===index?{...item,label:event.target.value}:item))}/><input className="crm-field" aria-label={`نشانی منبع ${index+1}`} dir="ltr" type="url" placeholder="https://" value={source.href} onChange={event=>set('sources',payload.sources.map((item,itemIndex)=>itemIndex===index?{...item,href:event.target.value}:item))}/><button type="button" className="icon-button" aria-label="حذف منبع" onClick={()=>set('sources',payload.sources.filter((_,itemIndex)=>itemIndex!==index))}>×</button></div>)}</div></EditorPanel>
      <EditorPanel title="دعوت به اقدام"><label>عنوان CTA<input className="crm-field" required value={payload.ctaTitle} onChange={event=>set('ctaTitle',event.target.value)}/></label><label>توضیح CTA<textarea className="crm-field" required rows={3} value={payload.ctaText} onChange={event=>set('ctaText',event.target.value)}/></label><div className="editor-grid"><label>متن دکمه<input className="crm-field" required value={payload.ctaLabel} onChange={event=>set('ctaLabel',event.target.value)}/></label><label>خدمت واتساپ<input className="crm-field" required value={payload.ctaService} onChange={event=>set('ctaService',event.target.value)}/></label></div></EditorPanel>
      <EditorPanel title="SEO"><label>عنوان SEO<input className="crm-field" maxLength={180} value={payload.seoTitle||''} placeholder={payload.title?`${payload.title} | پیکسل`:''} onChange={event=>set('seoTitle',event.target.value)}/><small className={(payload.seoTitle?.length||0)>60?'length-warning':''}>{toPersianNumber(payload.seoTitle?.length||0)} از حدود ۶۰ نویسه</small></label><label>توضیح SEO<textarea className="crm-field" rows={3} maxLength={320} value={payload.seoDescription||''} placeholder={payload.excerpt} onChange={event=>set('seoDescription',event.target.value)}/><small className={(payload.seoDescription?.length||0)>160?'length-warning':''}>{toPersianNumber(payload.seoDescription?.length||0)} از حدود ۱۶۰ نویسه</small></label></EditorPanel>
      <div className="editor-savebar"><button className="crm-primary" disabled={saving}>{saving?'در حال ذخیره…':'ذخیره پیش‌نویس'}</button>{row&&membership.role==='admin'&&<button type="button" className="text-button danger" onClick={()=>void archive()}>انتقال به آرشیو</button>}</div>
    </form><aside className="article-editor-summary"><strong>وضعیت محتوا</strong><span>{dirty?'تغییرات ذخیره‌نشده':'همه تغییرات ذخیره شده'}</span><dl><dt>بخش‌ها</dt><dd>{toPersianNumber(payload.sections.length)}</dd><dt>منابع</dt><dd>{toPersianNumber(payload.sources.length)}</dd><dt>زمان مطالعه</dt><dd>{toPersianNumber(payload.readingMinutesValue)} دقیقه</dd></dl>{row?.published_at&&<a href={`https://pxlgrid.design/articles/${row.slug}/`} target="_blank" rel="noreferrer">مشاهده نسخه فعلی سایت</a>}</aside></div>
    {previewOpen&&<div ref={previewDialogRef} className="article-preview-modal" role="dialog" aria-modal="true" aria-label="پیش‌نمایش مقاله" tabIndex={-1}><button ref={previewCloseRef} type="button" className="preview-close" onClick={()=>setPreviewOpen(false)} aria-label="بستن پیش‌نمایش"><Icon name="close"/></button><ArticleDetailContent article={{...payload,readingMinutes:`${payload.readingMinutesValue} دقیقه مطالعه`}}/></div>}
  </>;
}

function EditorPanel({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode}){return <section className="editor-panel"><header><h2>{title}</h2>{action}</header><div>{children}</div></section>}
