import { chromium } from 'playwright-core';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { validatePortfolioPayload } from '../supabase/functions/_shared/portfolio.ts';
import { portfolioFixtures } from '../src/portfolio-data.ts';

const base = process.env.PIXEL_TEST_URL || 'http://127.0.0.1:4173';
const browser = await chromium.launch({ executablePath: process.env.PIXEL_BROWSER_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const report = { viewports: [], errors: [], violations: [], requestsAfterSubmit: [], checks: [] };
await mkdir('outputs', { recursive: true });
try {
  const fixture = portfolioFixtures.find(item => item.payload.link === '/portfolio/roma/');
  assert.ok(fixture);
  assert.equal(validatePortfolioPayload(fixture.payload, 'concept', '00000000-0000-0000-0000-000000000001', fixture.id).theme, 'coffee');
  assert.doesNotMatch(await readFile('dist/sitemap.xml', 'utf8'), /\/portfolio\/roma/);
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  page.on('pageerror', error => report.errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') report.errors.push(message.text()); });
  await page.goto(`${base}/portfolio/roma/`);
  await page.evaluate(() => document.fonts.ready);
  await page.locator('#rm-name').waitFor();
  await page.waitForFunction(() => !document.querySelector('.rm-reserve-form fieldset').disabled);
  assert.match(await page.title(), /کافه روما/);
  assert.equal(await page.locator('meta[name="robots"]').getAttribute('content'), 'noindex, nofollow');
  assert.equal(await page.locator('h1').count(), 1);
  assert.ok(await page.getByText('کانسپت نمایشی پیکسل؛ کافهٔ واقعی نیست', { exact: true }).isVisible());
  for (const image of await page.locator('.roma-page img').all()) {
    await image.scrollIntoViewIfNeeded();
    await image.evaluate(element => element.decode());
    assert.ok(await image.evaluate(element => element.naturalWidth > 0));
  }
  const anchors = await page.locator('a[href^="#"]').evaluateAll(links => links.map(link => link.getAttribute('href')));
  for (const anchor of new Set(anchors)) assert.equal(await page.locator(anchor).count(), 1, `Missing anchor: ${anchor}`);
  assert.deepEqual(await page.locator('a:not([href^="#"])').evaluateAll(links => [...new Set(links.map(link => link.getAttribute('href')))]), ['/portfolio/']);
  for (const width of [360, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 1000 });
    await page.evaluate(() => window.scrollTo(0, 0));
    const state = await page.evaluate(() => ({ width: innerWidth, scrollWidth: document.documentElement.scrollWidth }));
    assert.ok(state.scrollWidth <= width, `Overflow at ${width}`);
    report.viewports.push(state);
    await page.screenshot({ path: `outputs/roma-${width}.png`, fullPage: true });
    if (width === 390 || width === 1440) {
      const audit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
      report.violations.push(...audit.violations.map(({ id, nodes }) => ({ width, id, nodes: nodes.map(({ target, failureSummary }) => ({ target, failureSummary })) })));
    }
  }
  const filters = page.getByRole('group', { name: 'دسته‌بندی منو' });
  await filters.getByRole('button', { name: 'قهوه', exact: true }).click();
  assert.equal(await page.locator('.rm-menu-item').count(), 3);
  await filters.getByRole('button', { name: 'شیرینی و دسر' }).click();
  assert.equal(await page.locator('.rm-menu-item').count(), 2);
  await filters.getByRole('button', { name: 'غذای سبک' }).click();
  assert.equal(await page.locator('.rm-menu-item').count(), 1);
  await page.getByRole('link', { name: 'مشاهده منوی کامل' }).click();
  assert.equal(await page.locator('.rm-menu-item').count(), 6);
  report.checks.push('All category filters and full-menu reset');
  await page.setViewportSize({ width: 390, height: 844 });
  const toggle = page.locator('.rm-mobile-nav summary');
  await toggle.click();
  assert.ok(await page.getByRole('navigation', { name: 'ناوبری موبایل' }).isVisible());
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.rm-mobile-nav').getAttribute('open'), null);
  await toggle.click();
  await page.getByRole('navigation', { name: 'ناوبری موبایل' }).getByRole('link', { name: 'منوی کافه' }).click();
  assert.equal(new URL(page.url()).hash, '#menu');
  assert.equal(await page.locator('.rm-mobile-nav').getAttribute('open'), null);
  await page.getByRole('button', { name: 'مسیریابی نمایشی' }).click();
  assert.match(await page.locator('#rm-contact-status').textContent(), /نشانی واقعی.*ندارد/);
  await page.locator('.rm-contact-actions').getByRole('link', { name: /اینستاگرام/ }).click();
  assert.match(await page.locator('#rm-contact-status').textContent(), /وجود ندارد/);
  report.checks.push('Mobile menu, Escape, anchors and fictional contact actions');
  await page.locator('.rm-header-reserve').click();
  assert.equal(new URL(page.url()).hash, '#reserve');
  const submit = page.getByRole('button', { name: 'امتحان رزرو میز' });
  await submit.click();
  assert.equal(await page.locator('#rm-name').evaluate(element => element.validity.valueMissing), true);
  await page.locator('#rm-name').fill('بازدیدکنندهٔ نمونه');
  await page.locator('#rm-phone').fill('123');
  await submit.click();
  assert.equal(await page.locator('#rm-phone').evaluate(element => element.validity.patternMismatch), true);
  await page.locator('#rm-phone').fill('۰۹۱۲۳۴۵۶۷۸۹');
  await page.locator('#rm-time').selectOption('afternoon');
  await page.waitForLoadState('networkidle');
  page.on('request', request => report.requestsAfterSubmit.push(request.url()));
  await submit.click();
  assert.equal(await page.locator('.rm-reserve-status').textContent(), 'این نسخه نمایشی است؛ میزی رزرو نشد.');
  assert.equal(await page.locator('#rm-phone').inputValue(), '');
  assert.deepEqual(report.requestsAfterSubmit, []);
  assert.deepEqual(await page.evaluate(() => ({ local: localStorage.length, session: sessionStorage.length })), { local: 0, session: 0 });
  report.checks.push('Required fields, phone validation, Persian digits, demo submit, no requests/storage');
  const noJs = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 390, height: 844 } });
  const staticPage = await noJs.newPage();
  await staticPage.goto(`${base}/portfolio/roma/`);
  assert.ok(await staticPage.locator('h1').isVisible());
  assert.equal(await staticPage.locator('.rm-menu-item').count(), 6);
  assert.ok(await staticPage.locator('#rm-name').isDisabled());
  await staticPage.locator('.rm-mobile-nav summary').click();
  assert.ok(await staticPage.getByRole('navigation', { name: 'ناوبری موبایل' }).isVisible());
  await staticPage.goto(`${base}/portfolio/`);
  assert.ok(await staticPage.getByRole('heading', { name: /کافه روما/ }).isVisible());
  await noJs.close();
  report.checks.push('Prerendered landing and portfolio, full menu and safe disabled form without JavaScript');
  await writeFile('outputs/roma-verification.json', JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
  assert.deepEqual(report.errors, []);
  assert.deepEqual(report.violations, []);
} finally { await browser.close(); }
