import { Icon, type IconName } from './Icons';
import { articles } from './articles.generated';

const services: { title: string; icon: IconName; items: string[] }[] = [
  { title: 'سئو تکنیکال', icon: 'code', items: ['بررسی Crawl و Indexing، Sitemap و Robots', 'Canonical و ساختار URL', 'رفع مشکلات فنی در محدوده توافق‌شده', 'Schema متناسب با اطلاعات واقعی کسب‌وکار', 'بهبود عملکرد و نمایش در موبایل'] },
  { title: 'سئو داخلی', icon: 'search', items: ['تحقیق عبارت‌های مرتبط با خدمات و مخاطب محلی', 'بهینه‌سازی Title و Meta Description', 'ساختار Heading و صفحات خدمات', 'لینک‌سازی داخلی و بهینه‌سازی تصاویر'] },
  { title: 'استراتژی محتوا', icon: 'layers', items: ['شناسایی سؤال‌ها و موضوعات مخاطبان', 'برنامه‌ریزی مقالات هدفمند', 'توسعه صفحات معرفی خدمات', 'اتصال مقالات به صفحات تجاری مرتبط'] },
  { title: 'سئوی محلی', icon: 'globe', items: ['هدف‌گذاری جستجوهای مرتبط با گرگان', 'بهینه‌سازی صفحات محلی با محتوای مستقل', 'لینک‌سازی بین خدمات و محتوای محلی مرتبط', 'بررسی اطلاعات واقعی و محدوده ارائه خدمات'] },
  { title: 'تحلیل و گزارش', icon: 'sales', items: ['بررسی Search Console با دسترسی مجاز', 'تحلیل Query، Impression و Click', 'بررسی CTR و عملکرد صفحات', 'شناسایی فرصت‌ها و گزارش دوره‌ای'] },
];
const audiences = [
  ['پزشکان و مراکز درمانی', 'برای معرفی روشن خدمات، تخصص و راه ارتباط با مرکز در جستجوهای مرتبط. محتوای تخصصی باید با تأیید مسئول مربوط آماده شود.'],
  ['شرکت‌ها و خدمات تخصصی', 'برای مخاطبی که پیش از درخواست همکاری، نوع خدمات و توانمندی شرکت را بررسی می‌کند.'],
  ['فروشگاه‌ها', 'برای معرفی محصولات و پاسخ به نیاز کاربری که درباره مشخصات، موجودی یا شیوه سفارش جستجو می‌کند.'],
  ['رستوران‌ها و کافه‌ها', 'برای کاربری که در گرگان به دنبال منو، محل، ساعت فعالیت و راه تماس یک مجموعه غذایی است.'],
  ['کسب‌وکارهای محلی', 'برای خدماتی که مشتریان آن‌ها از گرگان و اطراف آن هستند؛ با توضیح دقیق نوع خدمت و محدوده واقعی فعالیت.'],
];
const steps = [
  ['بررسی سایت', 'وضعیت فنی، صفحات فعلی، محتوا و فرصت‌های بهبود بررسی می‌شود.'],
  ['تحلیل جستجو', 'کلمات و موضوعات مرتبط با خدمات و مخاطبان هدف در گرگان مشخص می‌شوند.'],
  ['تدوین استراتژی', 'اولویت صفحات، محتوا و اصلاحات متناسب با شرایط سایت تعیین می‌شود.'],
  ['اجرا', 'اصلاحات فنی، سئو داخلی، محتوا و لینک‌سازی در محدوده توافق‌شده اجرا می‌شوند.'],
  ['تحلیل و بهینه‌سازی', 'داده‌های واقعی Search Console و عملکرد صفحات بررسی می‌شوند.'],
  ['گزارش', 'اقدامات، تغییرات و پیشنهاد قدم بعدی در دوره‌های توافق‌شده گزارش می‌شوند.'],
];
const questions = [
  ['سئو در گرگان چقدر زمان می‌برد؟', 'زمان ارزیابی به وضعیت سایت، رقابت حوزه، کلمات هدف و کیفیت و استمرار اجرا بستگی دارد. پس از بررسی اولیه، برنامه مشخص می‌شود؛ زمان یا نتیجه قطعی تضمین نمی‌شود.'],
  ['هزینه سئو در گرگان چقدر است؟', 'هزینه پس از بررسی سایت و تعیین محدوده کار اعلام می‌شود. تعداد صفحات هدف، نیاز محتوایی، وضعیت فنی و رقابت بر آن اثر دارند.'],
  ['آیا سئو فقط برای سایت‌های گرگان انجام می‌شود؟', 'خیر. خدمات برای کسب‌وکارهای محلی و غیرمحلی قابل ارائه است؛ این صفحه به نیاز کسب‌وکارهای فعال در گرگان اختصاص دارد.'],
  ['آیا رتبه اول گوگل را تضمین می‌کنید؟', 'خیر. رتبه گوگل قابل تضمین نیست. هدف، ساخت و بهینه‌سازی مسیر جذب ترافیک مرتبط است؛ محدوده اجرا و گزارش‌دهی پیش از همکاری مشخص می‌شود.'],
  ['آیا سئو شامل تولید محتوا هم می‌شود؟', 'تولید یا بهینه‌سازی محتوا می‌تواند بخشی از همکاری باشد. تعداد، نوع محتوا و مسئولیت ارائه اطلاعات تخصصی در پیشنهاد مشخص می‌شود.'],
  ['از کجا بفهمم سایت من به سئو نیاز دارد؟', 'بررسی فنی، صفحات و داده‌های جستجو کمک می‌کند مسائل و فرصت‌ها روشن شوند. برای شروع، درخواست بررسی رایگان سایت بدهید.'],
];

function AuditLink({ children = 'درخواست بررسی رایگان سایت' }: { children?: string }) {
  return <a className="button primary" href="/free-website-audit/">{children}<Icon name="arrow" size={18}/></a>;
}

export default function SeoGorganPage() {
  const relatedArticle = articles.find(article => article.slug === 'why-business-needs-website');
  return <div className="seo-service-page seo-gorgan-page web-design-page pricing-page">
    <section className="pricing-hero container" aria-labelledby="seo-gorgan-title"><div><span className="pricing-eyebrow"><span className="blue-dot"/> شناخت خدمات، مخاطب و جستجوی محلی</span><h1 id="seo-gorgan-title">خدمات سئو در گرگان<br/><span>برای رشد کسب‌وکار شما</span></h1><p>اگر کسب‌وکار شما در گرگان فعالیت می‌کند، حضور در نتایج جستجوی گوگل می‌تواند یکی از مسیرهای مهم جذب مشتری باشد. ما با بررسی وضعیت فعلی سایت، کلمات جستجوی مرتبط با کسب‌وکار شما و فرصت‌های موجود، یک مسیر سئوی متناسب با شرایط سایتتان طراحی و اجرا می‌کنیم.</p><div className="wd-actions"><AuditLink/><a className="wd-text-link" href="/seo/">مشاهده خدمات سئو <Icon name="arrow" size={18}/></a></div></div><aside className="pricing-hero-note"><span>از جستجو تا تصمیم</span><strong>کاربر چه چیزی<br/><bdi>درباره شما می‌خواهد بداند؟</bdi></strong><p>نوع خدمات، محدوده فعالیت، اطلاعات کاربردی و راه تماس؛ صفحه باید به سؤال‌های واقعی مخاطب محلی پاسخ بدهد، نه فقط نام شهر را تکرار کند.</p><a className="wd-text-link" href="#local-approach">تفاوت سئوی محلی <Icon name="arrow" size={16}/></a></aside></section>
    <section className="wd-trust" aria-labelledby="local-value"><div className="container wd-trust-inner"><div><h2 id="local-value">چرا سئو برای کسب‌وکارهای<br/><span>گرگان مهم است؟</span></h2></div><p>وقتی کاربر پیش از انتخاب یک خدمت یا محصول در گوگل جستجو می‌کند، سایت فرصتی برای معرفی کسب‌وکار و پاسخ به نیاز اوست. دیده‌شدن در جستجوهای مرتبط می‌تواند به آشنایی با برند، ورود به صفحه خدمات، درخواست مشاوره، تماس یا سفارش کمک کند. هدف فقط بالا آمدن یک کلمه نیست؛ مخاطب باید به خدمت مناسب برسد.</p></div></section>
    <section className="container wd-section" aria-labelledby="local-services"><div className="wd-section-heading"><div><span className="wd-section-index">۰۱ / کار روی سایت</span><h2 id="local-services">خدمات سئو برای<br/><span>کسب‌وکارهای گرگان</span></h2></div><p>از موانع فنی تا محتوای صفحات محلی؛ بخش‌های موردنیاز پس از بررسی سایت انتخاب می‌شوند.</p></div><div className="wd-type-grid">{services.map(({title,icon,items},index)=><article className="wd-type" key={title}><div className="wd-type-head"><span className="wd-icon"><Icon name={icon}/></span><span className="wd-index" aria-hidden="true">{String(index+1).padStart(2,'0')}</span></div><h3>{title}</h3><ul className="feature-list">{items.map(item=><li key={item}><Icon name="check" size={16}/><span>{item}</span></li>)}</ul></article>)}</div></section>
    <section id="local-approach" className="wd-deliverables" aria-labelledby="local-approach-title"><div className="container wd-deliverables-layout"><div className="wd-deliverables-copy"><span className="wd-section-index">۰۲ / تفاوت رویکرد محلی</span><h2 id="local-approach-title">سئوی محلی،<br/><span>فراتر از نام شهر.</span></h2><p>اضافه کردن «گرگان» به متن یا ساخت صفحات مشابه برای شهرهای مختلف، به‌تنهایی پاسخ نیاز کاربر نیست. هر صفحه باید بر خدمات واقعی و اطلاعات مستقل تکیه کند.</p></div><div className="wd-deliverables-list">{[['هدف جستجو و صفحه خدمات','کاربر به دنبال مقایسه خدمات است، اطلاعات محصول می‌خواهد یا آماده تماس است؟ ساختار صفحه بر این اساس بررسی می‌شود.'],['محتوای محلی و اطلاعات واقعی','نوع خدمت، محدوده فعالیت، ساعت کار و راه ارتباط فقط بر اساس اطلاعات تأییدشده کسب‌وکار درج می‌شوند.'],['لینک‌های داخلی مرتبط','مقاله، صفحه خدمت و اطلاعات محلی باید مسیر روشنی بسازند؛ بدون لینک‌سازی بی‌ربط یا صفحات تکراری.'],['اعتبار و شواهد قابل اتکا','نمونه‌ها و اطلاعاتی که کسب‌وکار واقعاً در اختیار دارد به کار می‌روند؛ آدرس دفتر، رضایت مشتری یا نتیجه ساختگی اضافه نمی‌شود.']].map(([title,description],index)=><article className="wd-deliverable" key={title}><span className="wd-deliverable-icon"><Icon name="check"/></span><span className="wd-deliverable-number" aria-hidden="true">{String(index+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></div></section>
    <section className="container wd-section" aria-labelledby="local-audiences"><div className="wd-section-heading"><div><span className="wd-section-index">۰۳ / کاربرد در کسب‌وکار</span><h2 id="local-audiences">سئو برای انواع<br/><span>کسب‌وکارهای گرگان</span></h2></div><p>این‌ها کاربردهای ممکن‌اند؛ اولویت هر سایت با شناخت خدمات و مسیر تصمیم‌گیری مشتری مشخص می‌شود.</p></div><div className="wd-reason-grid">{audiences.map(([title,description],index)=><article className="wd-reason" key={title}><span className="wd-reason-number" aria-hidden="true">{String(index+1).padStart(2,'0')}</span><h3>{title}</h3><p>{description}</p></article>)}</div><div className="seo-page-links"><a href="/web-design-gorgan/">هنوز سایت ندارید؟ طراحی سایت در گرگان</a>{relatedArticle && <a href={`/articles/${relatedArticle.slug}/`}>{relatedArticle.title}</a>}</div></section>
    <section className="container wd-section wd-process" aria-labelledby="local-process"><div className="wd-process-heading"><span className="wd-section-index">۰۴ / روند همکاری</span><h2 id="local-process">از بررسی وضعیت،<br/><span>تا اجرای اولویت‌ها.</span></h2><p>کار با شناخت سایت شروع می‌شود. برنامه و حجم فعالیت متناسب با شرایط پروژه تعریف می‌شوند و در همکاری مستمر، داده‌ها مسیر اصلاحات بعدی را مشخص می‌کنند.</p></div><div className="wd-steps"><span className="wd-process-track" aria-hidden="true"/>{steps.map(([title,description],index)=><article className="wd-step" key={title}><span className="wd-step-number" aria-hidden="true">{String(index+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></section>
    <section id="local-pricing" className="pricing-factors" aria-labelledby="local-pricing-title"><div className="container pricing-factors-inner"><div><span className="pricing-kicker">۰۵ / برآورد با محدوده روشن</span><h2 id="local-pricing-title">هزینه سئو در گرگان<br/><span>چگونه تعیین می‌شود؟</span></h2><p>هزینه سئو برای هر کسب‌وکار با توجه به وضعیت فعلی سایت، رقابت حوزه، تعداد صفحات، اهداف و حجم فعالیت موردنیاز تعیین می‌شود.</p><div className="wd-actions"><AuditLink>درخواست بررسی سایت</AuditLink><a className="wd-text-link" href="/seo/#seo-plans">مشاهده جزئیات خدمات و تعرفه‌های سئو <Icon name="arrow" size={16}/></a></div></div><ol>{[['وضعیت فنی','سایتی با ساختار مناسب، با سایتی که مشکل ایندکس دارد، به کار یکسان نیاز ندارد.'],['صفحات و محتوا','برخی سایت‌ها صفحات خدمات کامل دارند؛ برخی به صفحات هدف و محتوای بیشتری نیاز دارند.'],['رقابت و هدف','رقابت عبارت‌ها و خدمات اولویت‌دار، حجم تحلیل و اجرای موردنیاز را تغییر می‌دهند.'],['فعالیت و گزارش','محدوده کار، حجم ماهانه و دوره گزارش‌دهی پیش از شروع در پیشنهاد مشخص می‌شوند.']].map(([title,description],index)=><li key={title}><span>{String(index+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{description}</p></div></li>)}</ol></div></section>
    <section className="container wd-section" aria-labelledby="local-evidence"><div className="wd-section-heading"><div><span className="wd-section-index">۰۶ / مبنای ارزیابی</span><h2 id="local-evidence">چرا قبل از تعیین قیمت<br/><span>باید سایت بررسی شود؟</span></h2></div><p>حتی دو سایت در یک حوزه ممکن است نیازهای متفاوتی داشته باشند. به‌جای قیمت یکسان، ابتدا وضعیت فعلی را مشخص می‌کنیم، اهداف قابل اندازه‌گیری تعریف می‌شوند و عملکرد با داده‌های در دسترس Search Console بررسی می‌شود. نمایش، کلیک و عملکرد صفحات بررسی می‌شوند؛ افزایش آن‌ها از قبل تضمین نمی‌شود.</p></div><div className="seo-page-links"><a href="/seo/">جزئیات کامل خدمات سئو</a><a href="/pricing/">تعرفه طراحی سایت؛ جدا از هزینه سئو</a><a href="/request/">ثبت درخواست همکاری</a></div></section>
    <section className="container contact-section wd-contact" aria-labelledby="local-audit"><div className="closing-card"><div className="closing-orbit" aria-hidden="true"/><h2 id="local-audit">نمی‌دانید سایت شما از نظر سئو<br/><span>در چه وضعیتی قرار دارد؟</span></h2><p>قبل از شروع همکاری، وضعیت فعلی سایتتان را بررسی کنید و ببینید مهم‌ترین فرصت‌ها و مشکلات SEO سایت کجاست.</p><AuditLink/></div></section>
    <section className="container wd-section wd-faq" aria-labelledby="local-faq"><div className="wd-faq-heading"><span className="wd-section-index">قبل از شروع</span><h2 id="local-faq">پرسش‌های متداول<br/><span>درباره سئوی محلی</span></h2><a className="wd-text-link" href="/request/">درخواست مشاوره سئو در گرگان <Icon name="arrow" size={16}/></a></div><div className="wd-faq-list">{questions.map(([question,answer],index)=><details key={question}><summary><span className="wd-faq-index">{String(index+1).padStart(2,'0')}</span><span>{question}</span><Icon name="plus" size={18}/></summary><p>{answer}{index===1 && <> <a href="/seo/#seo-plans">محدوده و تعرفه‌های سئو</a> را ببینید و برای برآورد دقیق، <a href="/free-website-audit/">درخواست بررسی سایت</a> بدهید.</>}{index===5 && <> <a href="/free-website-audit/">ثبت درخواست بررسی رایگان</a></>}</p></details>)}</div></section>
  </div>;
}
