import { Contact } from './Contact';
import { Icon, type IconName } from './Icons';
import { PricingCard } from './PricingCards';
import type { PricingPlan } from './pricing';
import { articles } from './articles.generated';

const services: { title: string; subtitle: string; icon: IconName; items: string[] }[] = [
  { title: 'سئوی فنی', subtitle: 'Technical SEO', icon: 'code', items: ['بررسی خزش و ایندکس صفحات', 'بررسی Sitemap و Robots', 'Canonical و ساختار URL', 'رفع خطاهای فنی در محدوده توافق‌شده', 'داده‌های ساختاریافته متناسب با محتوا', 'عملکرد و سازگاری با موبایل'] },
  { title: 'بهینه‌سازی صفحات', subtitle: 'On-Page SEO', icon: 'search', items: ['تحقیق و هدف‌گذاری کلمات کلیدی', 'Title و Meta Description', 'ساختار تیترها و صفحات خدمات', 'لینک‌سازی داخلی', 'بهینه‌سازی تصاویر'] },
  { title: 'سئوی محتوا', subtitle: 'Content SEO', icon: 'layers', items: ['استراتژی و برنامه محتوایی', 'تولید یا بهینه‌سازی محتوای هدفمند', 'خوشه‌های موضوعی (Topic Cluster)', 'مقالات آموزشی و تجاری', 'اتصال محتوا به صفحات خدمات'] },
  { title: 'سئوی محلی', subtitle: 'Local SEO', icon: 'globe', items: ['بهینه‌سازی صفحات محلی', 'هدف‌گذاری جستجوهای مرتبط با محل فعالیت', 'ساختار صفحات محلی با محتوای کاربردی', 'لینک‌سازی داخلی بین صفحات مرتبط'] },
  { title: 'تحلیل و گزارش', subtitle: 'Analysis & Reporting', icon: 'sales', items: ['بررسی داده‌های Search Console با دسترسی مجاز', 'تحلیل عملکرد صفحات و عبارت‌های جستجو', 'بررسی نرخ کلیک (CTR)', 'شناسایی فرصت‌های جدید', 'گزارش دوره‌ای اقدامات و تغییرات'] },
];
const plans: readonly PricingPlan[] = [
  { id: 'technical', title: 'اصلاح زیرساخت سئو', audience: 'برای سایت‌هایی با موانع فنی یا شروع نامشخص', priceMillions: null, scope: 'یک پروژه با محدوده مشخص؛ بدون تعهد فعالیت ماهانه', features: ['بررسی وضعیت فنی و فهرست اولویت‌ها', 'اصلاح خطاهای فنی منتخب و ساختار صفحات', 'حجم اجرا بر اساس تعداد صفحات و خطاهای توافق‌شده', 'گزارش اولیه و جمع‌بندی پس از اجرای اصلاحات'], limit: 'تولید محتوا، سئوی مستمر و بازطراحی کامل سایت شامل این محدوده نیست.' },
  { id: 'service-pages', title: 'سئوی صفحات خدمات', audience: 'برای کسب‌وکارهای خدماتی و جستجوهای تجاری یا محلی', priceMillions: null, scope: 'همکاری ماهانه با تمرکز روی صفحات اولویت‌دار', features: ['تحقیق کلمات کلیدی و هدف هر صفحه', 'بهینه‌سازی محتوا، تیترها و لینک‌های داخلی', 'صفحات خدمات و محلی متناسب با نیاز پروژه', 'تعداد صفحات و حجم کار ماهانه در پیشنهاد مشخص می‌شود', 'گزارش ماهانه اقدامات و داده‌های در دسترس'], limit: 'تولید انبوه مقالات، توسعه امکانات جدید و اصلاحات فنی گسترده جداگانه برآورد می‌شوند.' },
  { id: 'continuous', title: 'سئوی مستمر و محتوا', audience: 'برای سایت‌هایی که به برنامه منظم اجرا و تحلیل نیاز دارند', priceMillions: null, scope: 'همکاری ماهانه در بخش فنی، صفحات و محتوا', features: ['استراتژی و اولویت‌های فنی و محتوایی', 'بهینه‌سازی صفحات و توسعه خوشه‌های موضوعی', 'تولید یا به‌روزرسانی محتوا در محدوده توافق‌شده', 'حجم ماهانه صفحات، محتوا و اصلاحات پیش از شروع تعیین می‌شود', 'گزارش ماهانه و بازنگری اولویت‌ها با Search Console'], limit: 'هزینه ابزارهای پولی، تبلیغات، خرید رسانه و بازطراحی سایت در تعرفه پایه نیست.' },
];
const steps = [
  ['بررسی وضعیت فعلی سایت', 'ساختار، صفحات مهم، وضعیت فنی و داده‌های موجود را بررسی می‌کنیم.'],
  ['تحلیل بازار و کلمات کلیدی', 'جستجوهای مرتبط با خدمات و نیاز مخاطب را مشخص می‌کنیم.'],
  ['تعیین اولویت‌ها و استراتژی', 'محدوده کار و اولویت صفحات، اصلاحات و محتوا روشن می‌شود.'],
  ['اجرای اصلاحات فنی و صفحات', 'موانع فنی و بخش‌های منتخب On-Page را بهبود می‌دهیم.'],
  ['توسعه محتوا و صفحات هدف', 'محتوا و صفحات را متناسب با برنامه توافق‌شده آماده می‌کنیم.'],
  ['بررسی داده‌های Search Console', 'تغییرات عبارت‌های جستجو، نمایش و کلیک صفحات را تحلیل می‌کنیم.'],
  ['بهینه‌سازی مستمر و گزارش‌دهی', 'اقدامات انجام‌شده را گزارش می‌کنیم و اولویت‌های بعدی را بازبینی می‌کنیم.'],
];
const questions = [
  ['سئو چقدر زمان می‌برد؟', 'زمان مشاهده اثر تغییرات به وضعیت اولیه سایت، رقابت و کیفیت اجرا بستگی دارد. پس از بررسی سایت، برنامه و دوره ارزیابی مشخص می‌شود؛ زمان نتیجه قطعی قابل تضمین نیست.'],
  ['آیا رتبه اول گوگل را تضمین می‌کنید؟', 'خیر. رتبه و نتیجه جستجو تضمین نمی‌شود. تعهد همکاری بر محدوده اجرا، گزارش‌دهی و بررسی داده‌ها است.'],
  ['هزینه سئو چگونه تعیین می‌شود؟', 'تعداد و وضعیت صفحات، خطاهای فنی، رقابت، نیاز محتوایی و حجم فعالیت ماهانه مبنای برآورد هستند. پیشنهاد مالی پس از بررسی سایت ارائه می‌شود.'],
  ['آیا تولید محتوا هم انجام می‌دهید؟', 'تولید و بهینه‌سازی محتوا می‌تواند در محدوده همکاری قرار بگیرد. تعداد، نوع و مسئولیت آماده‌سازی اطلاعات تخصصی پیش از شروع مشخص می‌شود.'],
  ['آیا سئو فقط برای سایت‌های جدید است؟', 'خیر. سایت جدید به ساختار مناسب نیاز دارد و سایت قدیمی هم ممکن است موانع فنی، محتوای نیازمند اصلاح یا فرصت‌های تازه داشته باشد.'],
  ['گزارش عملکرد سئو دریافت می‌کنم؟', 'بله. در همکاری ماهانه، گزارش اقدامات و داده‌های در دسترس ارائه می‌شود. پروژه اصلاح زیرساخت، گزارش اولیه و جمع‌بندی اجرای اصلاحات دارد.'],
  ['آیا خدمات Local SEO هم ارائه می‌دهید؟', 'بله. بهینه‌سازی صفحات و هدف‌گذاری جستجوهای محلی، بر اساس محل فعالیت و خدمات واقعی کسب‌وکار، قابل تعریف است.'],
  ['قبل از شروع همکاری وضعیت سایت بررسی می‌شود؟', 'بله. بررسی اولیه کمک می‌کند محدوده و اولویت‌ها مشخص شوند. می‌توانید از صفحه بررسی رایگان سایت شروع کنید.'],
  ['تفاوت سئو با تبلیغات گوگل چیست؟', 'سئو به حضور سایت در نتایج غیرتبلیغاتی مربوط است. تبلیغات گوگل مسیر جداگانه‌ای با بودجه تبلیغاتی دارد؛ هزینه تبلیغات در پلن‌های سئو نیست و پرداخت برای آگهی، رتبه طبیعی را تضمین نمی‌کند.'],
];

export default function SeoPage() {
  const related = articles.filter(article => article.slug === 'ai-agent-for-business' || article.slug === 'why-business-needs-website');
  return <div className="seo-service-page web-design-page pricing-page">
    <section className="pricing-hero container" aria-labelledby="seo-title"><div><span className="pricing-eyebrow"><span className="blue-dot"/> از بررسی سایت تا بهینه‌سازی مستمر</span><h1 id="seo-title">خدمات سئو سایت؛<br/><span>برای دیده‌شدن بیشتر و جذب مشتری از گوگل</span></h1><p>ساختار فنی، صفحات خدمات و محتوای سایت را بررسی و بهینه می‌کنیم. مسیر همکاری با شناخت وضعیت سایت شروع می‌شود و با اجرای اولویت‌ها، تحلیل داده‌ها و گزارش ادامه پیدا می‌کند.</p><div className="wd-actions"><Contact className="primary" location="seo-hero" service="مشاوره خدمات سئو">درخواست مشاوره سئو</Contact><a className="wd-text-link" href="#seo-plans">مشاهده تعرفه‌ها <Icon name="arrow" size={18}/></a></div></div><aside className="pricing-hero-note"><span>اولویت، پیش از اجرا</span><strong>کدام صفحه باید<br/><bdi>بهتر دیده شود؟</bdi></strong><p>از صفحات مهم کسب‌وکار شروع می‌کنیم؛ با هدف جذب بازدیدکننده مرتبط و ساده‌تر شدن مسیر آشنایی با خدمات و تماس.</p><a className="wd-text-link" href="/free-website-audit/">بررسی رایگان سایت <Icon name="arrow" size={16}/></a></aside></section>
    <section className="wd-trust" aria-labelledby="seo-value"><div className="container wd-trust-inner"><div><h2 id="seo-value">سئو فقط گرفتن رتبه نیست؛<br/><span>باید به کسب‌وکار وصل شود.</span></h2></div><p>جستجوی مرتبط، صفحه‌ای که نیاز مخاطب را پاسخ می‌دهد و مسیری روشن برای تماس؛ این‌ها کنار هم ارزش دارند. با بهبود ساختار و تجربه سایت، صفحات خدمات و محتوای هدفمند، زمینه حضور بهتر در جستجوهای تجاری را فراهم می‌کنیم.</p></div></section>
    <section className="container wd-section" aria-labelledby="seo-services"><div className="wd-section-heading"><div><span className="wd-section-index">۰۱ / محدوده خدمات</span><h2 id="seo-services">خدمات سئو ما</h2></div><p>این خدمات بر اساس نیاز سایت در پیشنهاد همکاری انتخاب می‌شوند؛ همه پروژه‌ها به حجم یکسانی از کار نیاز ندارند.</p></div><div className="wd-type-grid">{services.map(({title,subtitle,icon,items})=><article className="wd-type" key={title}><div className="wd-type-head"><span className="wd-icon"><Icon name={icon}/></span><span className="seo-service-label" lang="en" dir="ltr">{subtitle}</span></div><h3>{title}</h3><ul className="feature-list">{items.map(item=><li key={item}><Icon name="check" size={16}/><span>{item}</span></li>)}</ul></article>)}</div></section>
    <section className="wd-deliverables" aria-labelledby="seo-reasons"><div className="container wd-deliverables-layout"><div className="wd-deliverables-copy"><span className="wd-section-index">۰۲ / رویکرد همکاری</span><h2 id="seo-reasons">کار مشخص،<br/><span>تصمیم بر اساس داده.</span></h2><p>به‌جای وعده رتبه، درباره اقداماتی صحبت می‌کنیم که برای سایت شما قابل اجرا و قابل بررسی‌اند.</p></div><div className="wd-deliverables-list">{[['هدف تجاری روشن','صفحات معرفی خدمات و مسیر درخواست مشتری را در اولویت بررسی قرار می‌دهیم.'],['داده‌های واقعی','با دسترسی مجاز، داده‌های Search Console را برای فهم عملکرد صفحات تحلیل می‌کنیم.'],['اجرای هماهنگ','اصلاحات فنی، محتوا و لینک‌های داخلی در یک برنامه مرتبط پیش می‌روند.'],['گزارش قابل پیگیری','مشخص می‌کنیم چه کاری انجام شده، چه داده‌ای در دسترس است و قدم بعدی چیست.']].map(([title,description],index)=><article className="wd-deliverable" key={title}><span className="wd-deliverable-icon"><Icon name="check"/></span><span className="wd-deliverable-number" aria-hidden="true">{String(index+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></div></section>
    <section className="container wd-section wd-process" aria-labelledby="seo-process"><div className="wd-process-heading"><span className="wd-section-index">۰۳ / مسیر همکاری</span><h2 id="seo-process">فرآیند همکاری،<br/><span>از شناخت تا بهبود.</span></h2><p>سئو یک فرایند مستمر است. نتیجه به وضعیت اولیه سایت، رقابت، حوزه فعالیت و کیفیت اجرا بستگی دارد. در پروژه‌های مقطعی، مراحل اجرا و گزارش به محدوده همان پروژه محدود می‌شوند.</p></div><div className="wd-steps"><span className="wd-process-track" aria-hidden="true"/>{steps.map(([title,description],index)=><article className="wd-step" key={title}><span className="wd-step-number" aria-hidden="true">{String(index+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></section>
    <section id="seo-plans" className="container pricing-plans" aria-labelledby="seo-plans-title"><div className="pricing-section-heading"><div><span className="pricing-kicker">۰۴ / تعرفه و محدوده</span><h2 id="seo-plans-title">تعرفه‌های سئو،<br/><span>متناسب با وضعیت سایت.</span></h2></div><p>هزینه هر پلن به وضعیت سایت و حجم کار بستگی دارد. پس از بررسی، محدوده، فعالیت ماهانه و پیشنهاد مالی را پیش از شروع مشخص می‌کنیم.</p></div><div className="pricing-grid">{plans.map((plan,index)=><PricingCard key={plan.id} plan={plan} compact={false} index={index+1} priceLabel="پس از بررسی سایت" location="seo-plan" service={`مشاوره سئو؛ ${plan.title}`}/>)}</div><div className="pricing-terms"><h3>چه چیزهایی هزینه را تغییر می‌دهند؟</h3><p>وضعیت فنی، تعداد صفحات هدف، رقابت، حجم محتوا و نیاز به توسعه تعیین‌کننده‌اند. خدمات خارج از محدوده، ابزارهای پولی و هزینه‌های تبلیغات جداگانه برآورد می‌شوند. دسترسی به Search Console و اطلاعات تخصصی کسب‌وکار برای اجرای بخش‌های مربوط لازم است. رتبه یا نتیجه مشخص تضمین نمی‌شود.</p><a className="wd-text-link" href="/pricing/">تعرفه طراحی سایت، جدا از خدمات سئو <Icon name="arrow" size={16}/></a></div></section>
    <section className="wd-trust" aria-labelledby="seo-audiences"><div className="container wd-trust-inner"><div><h2 id="seo-audiences">برای کسب‌وکارهایی که<br/><span>مشتری آن‌ها جستجو می‌کند.</span></h2></div><p>شرکت‌ها و مجموعه‌های خدماتی، پزشکان و کلینیک‌ها، رستوران‌ها، فروشگاه‌ها، خدمات محلی و کسب‌وکارهای اینترنتی؛ مسیر کار بر اساس خدمات واقعی و نیاز مخاطبان هر سایت تعیین می‌شود.</p><div className="seo-page-links"><a href="/web-design/">اگر هنوز سایت ندارید: طراحی سایت</a><a href="/web-design-gorgan/">طراحی سایت برای کسب‌وکارهای گرگان</a><a href="/seo-gorgan/">خدمات سئو برای کسب‌وکارهای گرگان</a></div></div></section>
    <section className="container wd-section wd-faq" aria-labelledby="seo-faq"><div className="wd-faq-heading"><span className="wd-section-index">پیش از تصمیم</span><h2 id="seo-faq">پرسش‌های متداول<br/><span>درباره خدمات سئو</span></h2><Contact glass location="seo-faq" service="پرسش درباره خدمات سئو">سؤالم را بپرسم</Contact></div><div className="wd-faq-list">{questions.map(([question,answer],index)=><details key={question}><summary><span className="wd-faq-index">{String(index+1).padStart(2,'0')}</span><span>{question}</span><Icon name="plus" size={18}/></summary><p>{answer}</p></details>)}</div></section>
    {related.length>0 && <section className="container seo-reading" aria-labelledby="seo-reading"><h2 id="seo-reading">پیش از شروع، بیشتر بدانید</h2><div className="seo-page-links">{related.map(article=><a key={article.slug} href={`/articles/${article.slug}/`}>{article.title}<Icon name="arrow" size={16}/></a>)}</div><p>برای آشنایی با اصول حضور سایت در جستجو، <a href="https://developers.google.com/search/docs/fundamentals/seo-starter-guide" target="_blank" rel="noopener noreferrer">راهنمای رسمی سئو گوگل</a> را هم بخوانید.</p></section>}
    <section id="contact" className="container contact-section wd-contact" aria-labelledby="seo-contact"><div className="closing-card"><div className="closing-orbit" aria-hidden="true"/><h2 id="seo-contact">می‌خواهید بدانید سایت شما<br/><span>برای رشد در گوگل چه وضعیتی دارد؟</span></h2><p>از بررسی اولیه شروع کنید؛ سپس درباره اولویت‌ها و محدوده همکاری تصمیم بگیرید.</p><div className="wd-actions"><a className="button primary" href="/free-website-audit/">درخواست بررسی رایگان سایت <Icon name="arrow" size={18}/></a><a className="wd-text-link" href="/request/">ثبت درخواست همکاری <Icon name="arrow" size={18}/></a></div></div></section>
  </div>;
}
